config:
  csrf_check: true
  error_text: '[NAME] is NOT valid'
  success_text: '[NAME] is a valid [TYPE]'
definitions:
  email:  'email'
  contact_email:  'email'
  sales_email:  'email'
  phone:  'uk_telephone'
  tel:  'uk_telephone'
  telephone:  'uk_telephone'
  mobile: 'uk_mobile'
  mob:  'uk_mobile'
  postcode: 'postcode'
  post_code:  'postcode'
  textarea: 'text'